### ISSUE TITLE
Errors when installing tools

### ISSUE THREAD

**Issue by Ingerid** [CSTR-Edinburgh/Ossian#18]
I got the following error-message when running the `setup_tools.sh` script: 

`/bin/bash: clang: command not found
Makefile:239: recipe for target 'delta.o' failed
make[2]: *** [delta.o] Error 127
make[2]: Leaving directory '/mnt/c/Users/ild/OneDrive - University of Edinburgh/project/Ossian/tools/downloads/SPTK-3.6/bin/delta'
Makefile:317: recipe for target 'install-recursive' failed
make[1]: *** [install-recursive] Error 1
make[1]: Leaving directory '/mnt/c/Users/ild/OneDrive - University of Edinburgh/project/Ossian/tools/downloads/SPTK-3.6/bin'
Makefile:268: recipe for target 'install-recursive' failed
make: *** [install-recursive] Error 1
22`

I set up the $OSSIAN directory variable in a separate setup-script, and since the OneDrive-folder has spaces in it, I had to reassign `IFS=""` . Since this change did not follow along with the $OSSIAN variable, I had to set `IFS=""` in the `setup_tools.sh` script as well (so the path wouldn't get cut off when installing Merlin). Is that  what might cause the problems, or is it unrelated? I have tried to google the errors, but there doesn't seem to be any straight-forward answers to what is going wrong here.

**Comment by numan947** [comment]
Hi,
I think you don't have the proper dependencies installed. I followed [this](http://jrmeyer.github.io/tts/2017/09/15/Ossian-Merlin-demo.html) tutorial to install Ossian.
Thanks,
~Numan
