### ISSUE TITLE
Training issue

### ISSUE THREAD

**Issue by ken-arf** [CSTR-Edinburgh/Ossian#24]
I had a training issue previously posed in https://github.com/CSTR-Edinburgh/Ossian/issues/7.
When I run the following command
python ./scripts/train.py -s rss_toy_demo -l rm naive_01_nn

I had an error message like this
== Train voice (proc no. 6 (aligner))  ==
Train processor aligner

          Training aligner -- see /WORK/TTS/Ossian/train//rm/speakers/rss_toy_demo/naive_01_nn/processors/aligner/training/log.txt

  ERROR [+2319]  HERest: file name of vocabulary list expected
 FATAL ERROR - Terminating program /WORK/TTS/Ossian//tools/bin//HERest
Aligner training failed

The last couple of the file  /WORK/TTS/Ossian/train//rm/speakers/rss_toy_demo/naive_01_nn/processors/aligner/training/log.txt is shown below.
Reestimation failed: cmp.mmf not made

Step 3 in script /WORK/TTS/Ossian//scripts/acoustic_model_training/subrecipes/script/standard_alignment.sh failed, aborted!

Does anyone know the workaround for this issue?

**Comment by ken-arf** [comment]
I solved this issue.

**Comment by A-d-DASARE** [comment]
how did you solve?
