### ISSUE TITLE
Chinese front-end

### ISSUE THREAD

**Issue by wotulong** [CSTR-Edinburgh/Ossian#4]
What should I need to prepare to realize a Mandarin Chinese front-edn, are *.txt files and *.wav files enough? Is it need any additional operation to make a front-end for Chinese? Thanks.

**Comment by candlewill** [comment]
@wotulong  This maybe helps you: https://gist.github.com/candlewill/8141bbe9d6c4c6224be8d3b4c07723eb

All Chinese characters are converted to pinyin. Tones are kept, and represented as numbers 1-5.

**Comment by wotulong** [comment]
@candlewill ,Thank you! Do you have any result of your Chinese TTS system  :) ? Is "data_thchs30" can be applied?

**Comment by candlewill** [comment]
Yes, here is some of my generated voice: http://t.cn/RNqynkB . The training data I used is not public.

**Comment by wotulong** [comment]
@candlewill ,Thanks very much.The result is not as naturally as I think, what's the probably reason do you think of the problem, the front-end or the back-end?

**Comment by candlewill** [comment]
The front-end is too simple for Chinese.

**Comment by wotulong** [comment]
@candlewill 好的，谢谢指导！

**Comment by 493238731** [comment]
@candlewill  Thank you for giving this sample. Can you tell me how many hours speech you take to train?

**Comment by shartoo** [comment]
有另外一个中文TTS 前端 仓库，不知道是否可用。https://github.com/Jackiexiao/MTTS
