### ISSUE TITLE
how to train?

### ISSUE THREAD

**Issue by wotulong** [CSTR-Edinburgh/Ossian#5]
Is it possible to train the model with the .wav files which sample rate are 16000 and how to do?

**Comment by oliverwatts** [comment]
The recipe ` recipes/naive_01_nn.cfg` will handle data of any sample rate without you having to change anything. Note that its processor `speech_feature_extractor` is configured with `sample_rate=48000`: this means that any audio input at training will be resampled to this rate before feature extraction. Upsampling 16000Hz audio like this is naive but works reasonably well; if you change the rate, be prepared to experiment with adjusting other settings of this processor (e.g. probably `mcep_order` and definitely `alpha`).

**Comment by wotulong** [comment]
OK, It works, thanks.

**Comment by candlewill** [comment]
@oliverwatts If `sample_rate` is changed to 16000, how to calculate the value of `alpha` and `mcep_order`?
