### ISSUE TITLE
Training error

### ISSUE THREAD

**Issue by wotulong** [CSTR-Edinburgh/Ossian#7]
The command line is：
"python ./scripts/train.py -s rss_toy_demo -l rm naive_01_nn’‘

and the err msg:

'''
-- Gather corpus
 -- Train voice
/home/zhsk/Ossian-bak/Ossian/train//rm/speakers/rss_toy_demo/naive_01_nn
/home/zhsk/Ossian-bak/Ossian/voices//rm/rss_toy_demo/naive_01_nn
try loading config from python...
/home/zhsk/Ossian-bak/Ossian/recipes/naive_01_nn.cfg
{'state_contexts': [('start_time', './attribute::start'), ('end_time', './attribute::end'), ('htk_state', 'count(./preceding-sibling::state) + 1'), ('htk_monophone', './ancestor::segment/attribute::pronunciation'), ('ll_segment', './ancestor::segment/preceding::segment[2]/attribute::pronunciation'), ('l_segment', './ancestor::segment/preceding::segment[1]/attribute::pronunciation'), ('c_segment', './ancestor::segment/attribute::pronunciation'), ('r_segment', './ancestor::segment/following::segment[1]/attribute::pronunciation'), ('rr_segment', './ancestor::segment/following::segment[2]/attribute::pronunciation'), ('length_left_word', "count(ancestor::token/preceding::token[@token_class='word'][1]/descendant::segment)"), ('length_current_word', 'count(ancestor::token/descendant::segment)'), ('length_right_word', "count(ancestor::token/following::token[@token_class='word'][1]/descendant::segment)"), ('since_beginning_of_word', "count_Xs_since_start_Y('segment', 'token')"), ('till_end_of_word', "count_Xs_till_end_Y('segment', 'token')"), ('length_l_phrase_in_words', "count(ancestor::phrase/preceding::phrase[1]/descendant::token[@token_class='word'])"), ('length_c_phrase_in_words', "count(ancestor::phrase/descendant::token[@token_class='word'])"), ('length_r_phrase_in_words', "count(ancestor::phrase/following::phrase[1]/descendant::token[@token_class='word'])"), ('length_l_phrase_in_segments', 'count(ancestor::phrase/preceding::phrase[1]/descendant::segment)'), ('length_c_phrase_in_segments', 'count(ancestor::phrase/descendant::segment)'), ('length_r_phrase_in_segments', 'count(ancestor::phrase/following::phrase[1]/descendant::segment)'), ('since_phrase_start_in_segs', "count_Xs_since_start_Y('segment', 'phrase')"), ('till_phrase_end_in_segs', "count_Xs_till_end_Y('segment', 'phrase')"), ('since_phrase_start_in_words', 'count_Xs_since_start_Y(\'token[@token_class="word"]\', \'phrase\')'), ('till_phrase_end_in_words', 'count_Xs_till_end_Y(\'token[@token_class="word"]\', \'phrase\')'), ('since_start_sentence_in_segments', "count_Xs_since_start_Y('segment', 'utt')"), ('since_start_sentence_in_words', 'count_Xs_since_start_Y(\'token[@token_class="word"]\', \'utt\')'), ('since_start_sentence_in_phrases', "count_Xs_since_start_Y('phrase', 'utt')"), ('till_end_sentence_in_segments', "count_Xs_till_end_Y('segment', 'utt')"), ('till_end_sentence_in_words', 'count_Xs_till_end_Y(\'token[@token_class="word"]\', \'utt\')'), ('till_end_sentence_in_phrases', "count_Xs_till_end_Y('phrase', 'utt')"), ('length_sentence_in_segments', 'count(ancestor::utt/descendant::segment)'), ('length_sentence_in_words', "count(ancestor::utt/descendant::token[@token_class='word'])"), ('length_sentence_in_phrases', 'count(ancestor::utt/descendant::phrase)'), ('L_vsm_d1', "./ancestor::token/preceding::token[@token_class='word'][1]/attribute::vsm_d1"), ('C_vsm_d1', './ancestor::token/attribute::vsm_d1'), ('R_vsm_d1', "./ancestor::token/following::token[@token_class='word'][1]/attribute::vsm_d1"), ('L_vsm_d2', "./ancestor::token/preceding::token[@token_class='word'][1]/attribute::vsm_d2"), ('C_vsm_d2', './ancestor::token/attribute::vsm_d2'), ('R_vsm_d2', "./ancestor::token/following::token[@token_class='word'][1]/attribute::vsm_d2"), ('L_vsm_d3', "./ancestor::token/preceding::token[@token_class='word'][1]/attribute::vsm_d3"), ('C_vsm_d3', './ancestor::token/attribute::vsm_d3'), ('R_vsm_d3', "./ancestor::token/following::token[@token_class='word'][1]/attribute::vsm_d3"), ('L_vsm_d4', "./ancestor::token/preceding::token[@token_class='word'][1]/attribute::vsm_d4"), ('C_vsm_d4', './ancestor::token/attribute::vsm_d4'), ('R_vsm_d4', "./ancestor::token/following::token[@token_class='word'][1]/attribute::vsm_d4"), ('L_vsm_d5', "./ancestor::token/preceding::token[@token_class='word'][1]/attribute::vsm_d5"), ('C_vsm_d5', './ancestor::token/attribute::vsm_d5'), ('R_vsm_d5', "./ancestor::token/following::token[@token_class='word'][1]/attribute::vsm_d5"), ('L_vsm_d6', "./ancestor::token/preceding::token[@token_class='word'][1]/attribute::vsm_d6"), ('C_vsm_d6', './ancestor::token/attribute::vsm_d6'), ('R_vsm_d6', "./ancestor::token/following::token[@token_class='word'][1]/attribute::vsm_d6"), ('L_vsm_d7', "./ancestor::token/preceding::token[@token_class='word'][1]/attribute::vsm_d7"), ('C_vsm_d7', './ancestor::token/attribute::vsm_d7'), ('R_vsm_d7', "./ancestor::token/following::token[@token_class='word'][1]/attribute::vsm_d7"), ('L_vsm_d8', "./ancestor::token/preceding::token[@token_class='word'][1]/attribute::vsm_d8"), ('C_vsm_d8', './ancestor::token/attribute::vsm_d8'), ('R_vsm_d8', "./ancestor::token/following::token[@token_class='word'][1]/attribute::vsm_d8"), ('L_vsm_d9', "./ancestor::token/preceding::token[@token_class='word'][1]/attribute::vsm_d9"), ('C_vsm_d9', './ancestor::token/attribute::vsm_d9'), ('R_vsm_d9', "./ancestor::token/following::token[@token_class='word'][1]/attribute::vsm_d9"), ('L_vsm_d10', "./ancestor::token/preceding::token[@token_class='word'][1]/attribute::vsm_d10"), ('C_vsm_d10', './ancestor::token/attribute::vsm_d10'), ('R_vsm_d10', "./ancestor::token/following::token[@token_class='word'][1]/attribute::vsm_d10")], 'dur_label_maker': <FeatureDumper.FeatureDumper object at 0x7ff7f63ed3d0>, 'SKLDecisionTreePausePredictor': <class 'SKLProcessors.SKLDecisionTreePausePredictor'>, 'train_stages': [[<Tokenisers.RegexTokeniser object at 0x7ff7f63ed310>, <Phonetisers.NaivePhonetiser object at 0x7ff7f63edd50>, <VSMTagger.VSMTagger object at 0x7ff7f63edb50>], [<FeatureDumper.FeatureDumper object at 0x7ff7f63edbd0>, <FeatureExtractor.WorldExtractor object at 0x7ff7f63eddd0>, <Aligner.StateAligner object at 0x7ff7f63edc10>, <SKLProcessors.SKLDecisionTreePausePredictor object at 0x7ff7f63ede10>, <PhraseMaker.PhraseMaker object at 0x7ff7f63edcd0>, <FeatureDumper.FeatureDumper object at 0x7ff7f63edd10>], [<FeatureDumper.FeatureDumper object at 0x7ff7f63ed3d0>, <NN.NNDurationPredictor object at 0x7ff7f63edf90>, <FeatureDumper.FeatureDumper object at 0x7ff7f63ed390>, <NN.NNAcousticPredictor object at 0x7ff7f63edb10>]], 'PUNC_PATT': '[\\p{C}||\\p{P}||\\p{S}]', 'JUNCTURE_NODES': "//token[@token_class='space'] | //token[@token_class='punctuation']", 'WorldExtractor': <class 'FeatureExtractor.WorldExtractor'>, 'RegexTokeniser': <class 'Tokenisers.RegexTokeniser'>, 'current_dir': '/home/zhsk/Ossian-bak/Ossian/recipes', 'phrase_adder': <PhraseMaker.PhraseMaker object at 0x7ff7f63edcd0>, 'dur_data_maker': <FeatureDumper.FeatureDumper object at 0x7ff7f63edd10>, 'pause_predictor': <SKLProcessors.SKLDecisionTreePausePredictor object at 0x7ff7f63ede10>, 'speech_generation': [<FeatureDumper.FeatureDumper object at 0x7ff7f63ed3d0>, <NN.NNDurationPredictor object at 0x7ff7f63edf90>, <FeatureDumper.FeatureDumper object at 0x7ff7f63ed390>, <NN.NNAcousticPredictor object at 0x7ff7f63edb10>], 'runtime_stages': [[<Tokenisers.RegexTokeniser object at 0x7ff7f63ed310>, <Phonetisers.NaivePhonetiser object at 0x7ff7f63edd50>, <VSMTagger.VSMTagger object at 0x7ff7f63edb50>], [<SKLProcessors.SKLDecisionTreePausePredictor object at 0x7ff7f63ede10>, <PhraseMaker.PhraseMaker object at 0x7ff7f63edcd0>], [<FeatureDumper.FeatureDumper object at 0x7ff7f63ed3d0>, <NN.NNDurationPredictor object at 0x7ff7f63edf90>, <FeatureDumper.FeatureDumper object at 0x7ff7f63ed390>, <NN.NNAcousticPredictor object at 0x7ff7f63edb10>]], 'text_proc': [<Tokenisers.RegexTokeniser object at 0x7ff7f63ed310>, <Phonetisers.NaivePhonetiser object at 0x7ff7f63edd50>, <VSMTagger.VSMTagger object at 0x7ff7f63edb50>], 'acoustic_predictor': <NN.NNAcousticPredictor object at 0x7ff7f63edb10>, 'duration_predictor': <NN.NNDurationPredictor object at 0x7ff7f63edf90>, 'NNAcousticPredictor': <class 'NN.NNAcousticPredictor'>, 'align_label_dumper': <FeatureDumper.FeatureDumper object at 0x7ff7f63edbd0>, 'pause_predictor_features': [('response', './attribute::has_silence="yes"'), ('token_is_punctuation', './attribute::token_class="punctuation"'), ('since_start_utterance_in_words', "count(preceding::token[@token_class='word'])"), ('till_end_utterance_in_words', "count(following::token[@token_class='word'])"), ('L_vsm_d1', "./preceding::token[@token_class='word'][1]/attribute::vsm_d1"), ('C_vsm_d1', './attribute::vsm_d1'), ('R_vsm_d1', "./following::token[@token_class='word'][1]/attribute::vsm_d1"), ('L_vsm_d2', "./preceding::token[@token_class='word'][1]/attribute::vsm_d2"), ('C_vsm_d2', './attribute::vsm_d2'), ('R_vsm_d2', "./following::token[@token_class='word'][1]/attribute::vsm_d2"), ('L_vsm_d3', "./preceding::token[@token_class='word'][1]/attribute::vsm_d3"), ('C_vsm_d3', './attribute::vsm_d3'), ('R_vsm_d3', "./following::token[@token_class='word'][1]/attribute::vsm_d3"), ('L_vsm_d4', "./preceding::token[@token_class='word'][1]/attribute::vsm_d4"), ('C_vsm_d4', './attribute::vsm_d4'), ('R_vsm_d4', "./following::token[@token_class='word'][1]/attribute::vsm_d4"), ('L_vsm_d5', "./preceding::token[@token_class='word'][1]/attribute::vsm_d5"), ('C_vsm_d5', './attribute::vsm_d5'), ('R_vsm_d5', "./following::token[@token_class='word'][1]/attribute::vsm_d5"), ('L_vsm_d6', "./preceding::token[@token_class='word'][1]/attribute::vsm_d6"), ('C_vsm_d6', './attribute::vsm_d6'), ('R_vsm_d6', "./following::token[@token_class='word'][1]/attribute::vsm_d6"), ('L_vsm_d7', "./preceding::token[@token_class='word'][1]/attribute::vsm_d7"), ('C_vsm_d7', './attribute::vsm_d7'), ('R_vsm_d7', "./following::token[@token_class='word'][1]/attribute::vsm_d7"), ('L_vsm_d8', "./preceding::token[@token_class='word'][1]/attribute::vsm_d8"), ('C_vsm_d8', './attribute::vsm_d8'), ('R_vsm_d8', "./following::token[@token_class='word'][1]/attribute::vsm_d8"), ('L_vsm_d9', "./preceding::token[@token_class='word'][1]/attribute::vsm_d9"), ('C_vsm_d9', './attribute::vsm_d9'), ('R_vsm_d9', "./following::token[@token_class='word'][1]/attribute::vsm_d9"), ('L_vsm_d10', "./preceding::token[@token_class='word'][1]/attribute::vsm_d10"), ('C_vsm_d10', './attribute::vsm_d10'), ('R_vsm_d10', "./following::token[@token_class='word'][1]/attribute::vsm_d10")], 'PhraseMaker': <class 'PhraseMaker.PhraseMaker'>, 'alignment': [<FeatureDumper.FeatureDumper object at 0x7ff7f63edbd0>, <FeatureExtractor.WorldExtractor object at 0x7ff7f63eddd0>, <Aligner.StateAligner object at 0x7ff7f63edc10>, <SKLProcessors.SKLDecisionTreePausePredictor object at 0x7ff7f63ede10>, <PhraseMaker.PhraseMaker object at 0x7ff7f63edcd0>, <FeatureDumper.FeatureDumper object at 0x7ff7f63edd10>], 'VSMTagger': <class 'VSMTagger.VSMTagger'>, 'duration_data_contexts': [('state_1_nframes', '(./state[1]/attribute::end - ./state[1]/attribute::start) div 5'), ('state_2_nframes', '(./state[2]/attribute::end - ./state[2]/attribute::start) div 5'), ('state_3_nframes', '(./state[3]/attribute::end - ./state[3]/attribute::start) div 5'), ('state_4_nframes', '(./state[4]/attribute::end - ./state[4]/attribute::start) div 5'), ('state_5_nframes', '(./state[5]/attribute::end - ./state[5]/attribute::start) div 5')], 'phone_and_state_contexts': [('length_left_word', "count(ancestor::token/preceding::token[@token_class='word'][1]/descendant::segment)"), ('length_current_word', 'count(ancestor::token/descendant::segment)'), ('length_right_word', "count(ancestor::token/following::token[@token_class='word'][1]/descendant::segment)"), ('since_beginning_of_word', "count_Xs_since_start_Y('segment', 'token')"), ('till_end_of_word', "count_Xs_till_end_Y('segment', 'token')"), ('length_l_phrase_in_words', "count(ancestor::phrase/preceding::phrase[1]/descendant::token[@token_class='word'])"), ('length_c_phrase_in_words', "count(ancestor::phrase/descendant::token[@token_class='word'])"), ('length_r_phrase_in_words', "count(ancestor::phrase/following::phrase[1]/descendant::token[@token_class='word'])"), ('length_l_phrase_in_segments', 'count(ancestor::phrase/preceding::phrase[1]/descendant::segment)'), ('length_c_phrase_in_segments', 'count(ancestor::phrase/descendant::segment)'), ('length_r_phrase_in_segments', 'count(ancestor::phrase/following::phrase[1]/descendant::segment)'), ('since_phrase_start_in_segs', "count_Xs_since_start_Y('segment', 'phrase')"), ('till_phrase_end_in_segs', "count_Xs_till_end_Y('segment', 'phrase')"), ('since_phrase_start_in_words', 'count_Xs_since_start_Y(\'token[@token_class="word"]\', \'phrase\')'), ('till_phrase_end_in_words', 'count_Xs_till_end_Y(\'token[@token_class="word"]\', \'phrase\')'), ('since_start_sentence_in_segments', "count_Xs_since_start_Y('segment', 'utt')"), ('since_start_sentence_in_words', 'count_Xs_since_start_Y(\'token[@token_class="word"]\', \'utt\')'), ('since_start_sentence_in_phrases', "count_Xs_since_start_Y('phrase', 'utt')"), ('till_end_sentence_in_segments', "count_Xs_till_end_Y('segment', 'utt')"), ('till_end_sentence_in_words', 'count_Xs_till_end_Y(\'token[@token_class="word"]\', \'utt\')'), ('till_end_sentence_in_phrases', "count_Xs_till_end_Y('phrase', 'utt')"), ('length_sentence_in_segments', 'count(ancestor::utt/descendant::segment)'), ('length_sentence_in_words', "count(ancestor::utt/descendant::token[@token_class='word'])"), ('length_sentence_in_phrases', 'count(ancestor::utt/descendant::phrase)'), ('L_vsm_d1', "./ancestor::token/preceding::token[@token_class='word'][1]/attribute::vsm_d1"), ('C_vsm_d1', './ancestor::token/attribute::vsm_d1'), ('R_vsm_d1', "./ancestor::token/following::token[@token_class='word'][1]/attribute::vsm_d1"), ('L_vsm_d2', "./ancestor::token/preceding::token[@token_class='word'][1]/attribute::vsm_d2"), ('C_vsm_d2', './ancestor::token/attribute::vsm_d2'), ('R_vsm_d2', "./ancestor::token/following::token[@token_class='word'][1]/attribute::vsm_d2"), ('L_vsm_d3', "./ancestor::token/preceding::token[@token_class='word'][1]/attribute::vsm_d3"), ('C_vsm_d3', './ancestor::token/attribute::vsm_d3'), ('R_vsm_d3', "./ancestor::token/following::token[@token_class='word'][1]/attribute::vsm_d3"), ('L_vsm_d4', "./ancestor::token/preceding::token[@token_class='word'][1]/attribute::vsm_d4"), ('C_vsm_d4', './ancestor::token/attribute::vsm_d4'), ('R_vsm_d4', "./ancestor::token/following::token[@token_class='word'][1]/attribute::vsm_d4"), ('L_vsm_d5', "./ancestor::token/preceding::token[@token_class='word'][1]/attribute::vsm_d5"), ('C_vsm_d5', './ancestor::token/attribute::vsm_d5'), ('R_vsm_d5', "./ancestor::token/following::token[@token_class='word'][1]/attribute::vsm_d5"), ('L_vsm_d6', "./ancestor::token/preceding::token[@token_class='word'][1]/attribute::vsm_d6"), ('C_vsm_d6', './ancestor::token/attribute::vsm_d6'), ('R_vsm_d6', "./ancestor::token/following::token[@token_class='word'][1]/attribute::vsm_d6"), ('L_vsm_d7', "./ancestor::token/preceding::token[@token_class='word'][1]/attribute::vsm_d7"), ('C_vsm_d7', './ancestor::token/attribute::vsm_d7'), ('R_vsm_d7', "./ancestor::token/following::token[@token_class='word'][1]/attribute::vsm_d7"), ('L_vsm_d8', "./ancestor::token/preceding::token[@token_class='word'][1]/attribute::vsm_d8"), ('C_vsm_d8', './ancestor::token/attribute::vsm_d8'), ('R_vsm_d8', "./ancestor::token/following::token[@token_class='word'][1]/attribute::vsm_d8"), ('L_vsm_d9', "./ancestor::token/preceding::token[@token_class='word'][1]/attribute::vsm_d9"), ('C_vsm_d9', './ancestor::token/attribute::vsm_d9'), ('R_vsm_d9', "./ancestor::token/following::token[@token_class='word'][1]/attribute::vsm_d9"), ('L_vsm_d10', "./ancestor::token/preceding::token[@token_class='word'][1]/attribute::vsm_d10"), ('C_vsm_d10', './ancestor::token/attribute::vsm_d10'), ('R_vsm_d10', "./ancestor::token/following::token[@token_class='word'][1]/attribute::vsm_d10")], 'word_vector_tagger': <VSMTagger.VSMTagger object at 0x7ff7f63edb50>, 'inspect': <module 'inspect' from '/usr/lib/python2.7/inspect.pyc'>, 'tokenisation_pattern': '(\\p{Z}*[\\p{C}||\\p{P}||\\p{S}]*\\p{Z}+|\\p{Z}*[\\p{C}||\\p{P}||\\p{S}]+\\Z)', 'aligner': <Aligner.StateAligner object at 0x7ff7f63edc10>, 'sys': <module 'sys' (built-in)>, 'dnn_label_maker': <FeatureDumper.FeatureDumper object at 0x7ff7f63ed390>, 'NaivePhonetiser': <class 'Phonetisers.NaivePhonetiser'>, 'tokeniser': <Tokenisers.RegexTokeniser object at 0x7ff7f63ed310>, 'LETTER_PATT': '[\\p{L}||\\p{N}||\\p{M}]', 'AcousticModelWorld': <class 'AcousticModel.AcousticModelWorld'>, 'speech_feature_extractor': <FeatureExtractor.WorldExtractor object at 0x7ff7f63eddd0>, 'dim': 10, 'c': <module 'default.const' from '/home/zhsk/Ossian-bak/Ossian/scripts/default/const.py'>, 'FeatureDumper': <class 'FeatureDumper.FeatureDumper'>, 'word_vsm_dim': 10, 'speech_coding_config': {'delta_delta_window': '1.0 -2.0 1.0', 'static_window': '1', 'order': 59, 'delta_window': '-0.5 0.0 0.5'}, 'pause_prediction': [<SKLProcessors.SKLDecisionTreePausePredictor object at 0x7ff7f63ede10>, <PhraseMaker.PhraseMaker object at 0x7ff7f63edcd0>], 'i': 5, 'SPACE_PATT': '\\p{Z}', 'PUNC_OR_SPACE_PATT': '[\\p{Z}||\\p{C}||\\p{P}||\\p{S}]', 'phonetiser': <Phonetisers.NaivePhonetiser object at 0x7ff7f63edd50>, 'NNDurationPredictor': <class 'NN.NNDurationPredictor'>, 'os': <module 'os' from '/usr/lib/python2.7/os.pyc'>, 'phone_contexts': [('htk_monophone', './attribute::pronunciation'), ('start_time', './attribute::start'), ('end_time', './attribute::end'), ('ll_segment', 'preceding::segment[2]/attribute::pronunciation'), ('l_segment', 'preceding::segment[1]/attribute::pronunciation'), ('c_segment', './attribute::pronunciation'), ('r_segment', 'following::segment[1]/attribute::pronunciation'), ('rr_segment', 'following::segment[2]/attribute::pronunciation'), ('length_left_word', "count(ancestor::token/preceding::token[@token_class='word'][1]/descendant::segment)"), ('length_current_word', 'count(ancestor::token/descendant::segment)'), ('length_right_word', "count(ancestor::token/following::token[@token_class='word'][1]/descendant::segment)"), ('since_beginning_of_word', "count_Xs_since_start_Y('segment', 'token')"), ('till_end_of_word', "count_Xs_till_end_Y('segment', 'token')"), ('length_l_phrase_in_words', "count(ancestor::phrase/preceding::phrase[1]/descendant::token[@token_class='word'])"), ('length_c_phrase_in_words', "count(ancestor::phrase/descendant::token[@token_class='word'])"), ('length_r_phrase_in_words', "count(ancestor::phrase/following::phrase[1]/descendant::token[@token_class='word'])"), ('length_l_phrase_in_segments', 'count(ancestor::phrase/preceding::phrase[1]/descendant::segment)'), ('length_c_phrase_in_segments', 'count(ancestor::phrase/descendant::segment)'), ('length_r_phrase_in_segments', 'count(ancestor::phrase/following::phrase[1]/descendant::segment)'), ('since_phrase_start_in_segs', "count_Xs_since_start_Y('segment', 'phrase')"), ('till_phrase_end_in_segs', "count_Xs_till_end_Y('segment', 'phrase')"), ('since_phrase_start_in_words', 'count_Xs_since_start_Y(\'token[@token_class="word"]\', \'phrase\')'), ('till_phrase_end_in_words', 'count_Xs_till_end_Y(\'token[@token_class="word"]\', \'phrase\')'), ('since_start_sentence_in_segments', "count_Xs_since_start_Y('segment', 'utt')"), ('since_start_sentence_in_words', 'count_Xs_since_start_Y(\'token[@token_class="word"]\', \'utt\')'), ('since_start_sentence_in_phrases', "count_Xs_since_start_Y('phrase', 'utt')"), ('till_end_sentence_in_segments', "count_Xs_till_end_Y('segment', 'utt')"), ('till_end_sentence_in_words', 'count_Xs_till_end_Y(\'token[@token_class="word"]\', \'utt\')'), ('till_end_sentence_in_phrases', "count_Xs_till_end_Y('phrase', 'utt')"), ('length_sentence_in_segments', 'count(ancestor::utt/descendant::segment)'), ('length_sentence_in_words', "count(ancestor::utt/descendant::token[@token_class='word'])"), ('length_sentence_in_phrases', 'count(ancestor::utt/descendant::phrase)'), ('L_vsm_d1', "./ancestor::token/preceding::token[@token_class='word'][1]/attribute::vsm_d1"), ('C_vsm_d1', './ancestor::token/attribute::vsm_d1'), ('R_vsm_d1', "./ancestor::token/following::token[@token_class='word'][1]/attribute::vsm_d1"), ('L_vsm_d2', "./ancestor::token/preceding::token[@token_class='word'][1]/attribute::vsm_d2"), ('C_vsm_d2', './ancestor::token/attribute::vsm_d2'), ('R_vsm_d2', "./ancestor::token/following::token[@token_class='word'][1]/attribute::vsm_d2"), ('L_vsm_d3', "./ancestor::token/preceding::token[@token_class='word'][1]/attribute::vsm_d3"), ('C_vsm_d3', './ancestor::token/attribute::vsm_d3'), ('R_vsm_d3', "./ancestor::token/following::token[@token_class='word'][1]/attribute::vsm_d3"), ('L_vsm_d4', "./ancestor::token/preceding::token[@token_class='word'][1]/attribute::vsm_d4"), ('C_vsm_d4', './ancestor::token/attribute::vsm_d4'), ('R_vsm_d4', "./ancestor::token/following::token[@token_class='word'][1]/attribute::vsm_d4"), ('L_vsm_d5', "./ancestor::token/preceding::token[@token_class='word'][1]/attribute::vsm_d5"), ('C_vsm_d5', './ancestor::token/attribute::vsm_d5'), ('R_vsm_d5', "./ancestor::token/following::token[@token_class='word'][1]/attribute::vsm_d5"), ('L_vsm_d6', "./ancestor::token/preceding::token[@token_class='word'][1]/attribute::vsm_d6"), ('C_vsm_d6', './ancestor::token/attribute::vsm_d6'), ('R_vsm_d6', "./ancestor::token/following::token[@token_class='word'][1]/attribute::vsm_d6"), ('L_vsm_d7', "./ancestor::token/preceding::token[@token_class='word'][1]/attribute::vsm_d7"), ('C_vsm_d7', './ancestor::token/attribute::vsm_d7'), ('R_vsm_d7', "./ancestor::token/following::token[@token_class='word'][1]/attribute::vsm_d7"), ('L_vsm_d8', "./ancestor::token/preceding::token[@token_class='word'][1]/attribute::vsm_d8"), ('C_vsm_d8', './ancestor::token/attribute::vsm_d8'), ('R_vsm_d8', "./ancestor::token/following::token[@token_class='word'][1]/attribute::vsm_d8"), ('L_vsm_d9', "./ancestor::token/preceding::token[@token_class='word'][1]/attribute::vsm_d9"), ('C_vsm_d9', './ancestor::token/attribute::vsm_d9'), ('R_vsm_d9', "./ancestor::token/following::token[@token_class='word'][1]/attribute::vsm_d9"), ('L_vsm_d10', "./ancestor::token/preceding::token[@token_class='word'][1]/attribute::vsm_d10"), ('C_vsm_d10', './ancestor::token/attribute::vsm_d10'), ('R_vsm_d10', "./ancestor::token/following::token[@token_class='word'][1]/attribute::vsm_d10")], 'StateAligner': <class 'Aligner.StateAligner'>}
train
Cannot load NN model from model_dir: /home/zhsk/Ossian-bak/Ossian/train//rm/speakers/rss_toy_demo/naive_01_nn/processors/duration_predictor -- not trained yet
Cannot load NN model from model_dir: /home/zhsk/Ossian-bak/Ossian/train//rm/speakers/rss_toy_demo/naive_01_nn/processors/acoustic_predictor -- not trained yet

== Train voice (proc no. 1 (word_splitter))  ==
Train processor word_splitter
RegexTokeniser requires no training
          Applying processor word_splitter
p p p p p pp pp p p p pp p pp p p p pp pp p p p pp

== Train voice (proc no. 2 (segment_adder))  ==
Train processor segment_adder
NaivePhonetiser requires no training
          Applying processor segment_adder
p p pp p pp p pp p p pp p p pp p p pp p p pp p p p

== Train voice (proc no. 3 (word_vector_tagger))  ==
Train processor word_vector_tagger
Count types...
Assemble cooccurance matrix...
Factorise cooccurance matrix...
Write output to /home/zhsk/Ossian-bak/Ossian/train//rm/speakers/rss_toy_demo/naive_01_nn/processors/word_vector_tagger/table_file.table
          Applying processor word_vector_tagger
p p p p p p p p p p p p p p p p p p p p p p p p p p p p p 

== Train voice (proc no. 4 (feature_dumper))  ==
Train processor feature_dumper
          Applying processor feature_dumper
p p pp p pp p pp p p pp p p pp p pp p p pp p p p p

== Train voice (proc no. 5 (acoustic_feature_extractor))  ==
Train processor acoustic_feature_extractor
          Applying processor acoustic_feature_extractor
pppppp p p p p pp pp p p p p p p p p p p p p p p p

== Train voice (proc no. 6 (aligner))  ==
Train processor aligner

          Training aligner -- see /home/zhsk/Ossian-bak/Ossian/train//rm/speakers/rss_toy_demo/naive_01_nn/processors/aligner/training/log.txt

  ERROR [+2319]  HERest: file name of vocabulary list expected
 FATAL ERROR - Terminating program /home/zhsk/Ossian-bak/Ossian//tools/bin//HERest
’‘’

**Comment by oliverwatts** [comment]
Can you share the log file generated during aligner training (/home/zhsk/Ossian-bak/Ossian/train//rm/speakers/rss_toy_demo/naive_01_nn/processors/aligner/training/log.txt)?

**Comment by wotulong** [comment]
It works now, thanks.

**Comment by Pallavimeeami** [comment]
How you solved this issue? Iam getting same error?

Can you please help me? Iam running this code in ubuntu 16.04

**Comment by Pallavimeeami** [comment]
rases', 'count(ancestor::utt/descendant::phrase)'), ('L_vsm_d1', "./ancestor::token/preceding::token[@token_class='word'][1]/attribute::vsm_d1"), ('C_vsm_d1', './ancestor::token/attribute::vsm_d1'), ('R_vsm_d1', "./ancestor::token/following::token[@token_class='word'][1]/attribute::vsm_d1"), ('L_vsm_d2', "./ancestor::token/preceding::token[@token_class='word'][1]/attribute::vsm_d2"), ('C_vsm_d2', './ancestor::token/attribute::vsm_d2'), ('R_vsm_d2', "./ancestor::token/following::token[@token_class='word'][1]/attribute::vsm_d2"), ('L_vsm_d3', "./ancestor::token/preceding::token[@token_class='word'][1]/attribute::vsm_d3"), ('C_vsm_d3', './ancestor::token/attribute::vsm_d3'), ('R_vsm_d3', "./ancestor::token/following::token[@token_class='word'][1]/attribute::vsm_d3"), ('L_vsm_d4', "./ancestor::token/preceding::token[@token_class='word'][1]/attribute::vsm_d4"), ('C_vsm_d4', './ancestor::token/attribute::vsm_d4'), ('R_vsm_d4', "./ancestor::token/following::token[@token_class='word'][1]/attribute::vsm_d4"), ('L_vsm_d5', "./ancestor::token/preceding::token[@token_class='word'][1]/attribute::vsm_d5"), ('C_vsm_d5', './ancestor::token/attribute::vsm_d5'), ('R_vsm_d5', "./ancestor::token/following::token[@token_class='word'][1]/attribute::vsm_d5"), ('L_vsm_d6', "./ancestor::token/preceding::token[@token_class='word'][1]/attribute::vsm_d6"), ('C_vsm_d6', './ancestor::token/attribute::vsm_d6'), ('R_vsm_d6', "./ancestor::token/following::token[@token_class='word'][1]/attribute::vsm_d6"), ('L_vsm_d7', "./ancestor::token/preceding::token[@token_class='word'][1]/attribute::vsm_d7"), ('C_vsm_d7', './ancestor::token/attribute::vsm_d7'), ('R_vsm_d7', "./ancestor::token/following::token[@token_class='word'][1]/attribute::vsm_d7"), ('L_vsm_d8', "./ancestor::token/preceding::token[@token_class='word'][1]/attribute::vsm_d8"), ('C_vsm_d8', './ancestor::token/attribute::vsm_d8'), ('R_vsm_d8', "./ancestor::token/following::token[@token_class='word'][1]/attribute::vsm_d8"), ('L_vsm_d9', "./ancestor::token/preceding::token[@token_class='word'][1]/attribute::vsm_d9"), ('C_vsm_d9', './ancestor::token/attribute::vsm_d9'), ('R_vsm_d9', "./ancestor::token/following::token[@token_class='word'][1]/attribute::vsm_d9"), ('L_vsm_d10', "./ancestor::token/preceding::token[@token_class='word'][1]/attribute::vsm_d10"), ('C_vsm_d10', './ancestor::token/attribute::vsm_d10'), ('R_vsm_d10', "./ancestor::token/following::token[@token_class='word'][1]/attribute::vsm_d10")], 'StateAligner': <class 'Aligner.StateAligner'>}
train
Cannot load NN model from model_dir: /home/user/Ossian/train//rm/speakers/rss_toy_demo/naive_01_nn/processors/duration_predictor -- not trained yet
Cannot load NN model from model_dir: /home/user/Ossian/train//rm/speakers/rss_toy_demo/naive_01_nn/processors/acoustic_predictor -- not trained yet


== Train voice (proc no. 1 (word_splitter))  ==
Train processor word_splitter
RegexTokeniser requires no training
          Applying processor word_splitter
u u u u u u uu u u u u uu u u u u u uu u u u u u u u u

== Train voice (proc no. 2 (segment_adder))  ==
Train processor segment_adder
NaivePhonetiser requires no training
          Applying processor segment_adder
u u u u u u uu u u u u u uu u u u u u uu u u u u u u u

== Train voice (proc no. 3 (word_vector_tagger))  ==
          Applying processor word_vector_tagger
u u u u u u u u u u u u u u u u u u u u u u u u u u u u u 

== Train voice (proc no. 4 (feature_dumper))  ==
Train processor feature_dumper
FeatureDumper already trained -- questions exist:
/home/user/Ossian/train//rm/speakers/rss_toy_demo/naive_01_nn//SomeFileName
          Applying processor feature_dumper
u u u u u u uu u u u u u uu u u u u u uu u u u u u u u

== Train voice (proc no. 5 (acoustic_feature_extractor))  ==
Train processor acoustic_feature_extractor
          Applying processor acoustic_feature_extractor
u u u u u u uu u u u u u uu u u u u u uu u u u u u u u

== Train voice (proc no. 6 (aligner))  ==
Train processor aligner

          Training aligner -- see /home/user/Ossian/train//rm/speakers/rss_toy_demo/naive_01_nn/processors/aligner/training/log.txt

sh: 1: /home/user/Ossian//tools/bin//HLEd: not found
sh: 1: /home/user/Ossian//tools/bin//HLEd: not found
Aligner training failed
(venv)




This is the log of screen
